apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-service-key
  name: dns-service-tcp
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    k8s-app: kube-dns
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-service-key
  name: dns-service-udp
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    k8s-app: kube-dns
