---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loadgenerator
  namespace: microservices-demo
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: semver:~v0.0
spec:
  releaseName: loadgenerator
  helmVersion: v3
  chart:
    git: git@gitlab.com:solomon585858/microservices-demo.git
    ref: main
    path: deploy/charts/loadgenerator
  values:
    image:
      repository: solomon5858558/loadgenerator
      tag: v0.0.1
    ingress:
      host: boutique.35.205.240.67.nip.io

